server:
    port: 8081
    tomcat:
      accept-count: 1000
      max-threads: 800
      min-spare-threads: 100
mybatis:
    mapper-locations: classpath:mapping/*.xml
    config-location: classpath:mybatis.cfg.xml

spring:
  application:
    name: miao-sha
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.21.197:3306/miaosha?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 50
      validation-query: SELECT 1
      test-while-idle: true
      aop-patterns: com.zmh.miaosha.*
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: 192.168.150.9
    port: 6379
    database: 0
    password:
    timeout: 300000ms
    jedis:
      pool:
        max-active: 50
        min-idle: 10
        max-wait: -1ms




